### ISSUE TITLE
Polydev breaks Polymer website (and other websites)

### ISSUE THREAD

**Issue by davidrleonard** [PolymerLabs/polydev#37]
### Description: 
The Polydev plugin is causing some serious issues that prevent browsing relevant Polymer Project documentation or other websites with the script enabled. I know its recommended to install the plugin on a different profile in Chrome, but it seems inconvenient that the plugin specifically breaks the https://www.polymer-project.org/1.0/ website and the documentation hosted on it.

### Issue: 
When I visit https://www.polymer-project.org/1.0/ website with the Polydev Chrome plugin installed, the plugin prevents scripts on the page from running successfully and prevents the page UI from being drawn correctly (the header and logos no longer resize and display correctly). 

When I've left the plugin running in the background, I've noticed it causes similar TypeErrors `Cannot read property '_bound' of null` on other websites and breaks functionality.

### Screenshot of Polymer Project website with plugin installed:
![image](https://cloud.githubusercontent.com/assets/6456757/20402055/093b8df2-acb0-11e6-897b-dfa4ce727338.png)

### Relevant error log from the Chrome console:
```
Uncaught TypeError: Cannot read property '_bound' of null
    at HTMLDocument.obj.removeEventListener (polydev/vendor/zone-microtask.js:995:15)
    at HTMLElement._resetFocusedContent (https://www.polymer-project.org/elements/elements.js:18:20083)
    at HTMLElement._complexObserverEffect (https://www.polymer-project.org/elements/elements.js:13:12758)
    at HTMLElement._effectEffects (https://www.polymer-project.org/elements/elements.js:13:10019)
    at HTMLElement._propertySetter (https://www.polymer-project.org/elements/elements.js:13:9767)
    at HTMLElement.__setProperty (https://www.polymer-project.org/elements/elements.js:13:9891)
    at HTMLElement._applyConfig (https://www.polymer-project.org/elements/elements.js:13:20952)
    at HTMLElement._afterClientsReady (https://www.polymer-project.org/elements/elements.js:13:20819)
    at HTMLElement._ready (https://www.polymer-project.org/elements/elements.js:11:16053)
    at HTMLElement._readyClients (https://www.polymer-project.org/elements/elements.js:11:16212)
```

### Environment:
OS: OSX 10.11.6
Chrome build: 54.0.2840.87
Polydev build: 0.0.6

### Thanks!
Thanks for providing this plugin. Let me know if I can provide you with any additional information to help you resolve the problem.

**Comment by rictic** [comment]
Thanks for filing this issue! This should be fixed in v0.0.7 which was just merged in #35 and published. Please file a new issue if you see any more problems like this.
